[NON-MODULAR] Volume mixer
DopplerShift13/DopplerShift pull request #181
Opened 2024-10-19 06:43 UTC by W4rd3nn

## About The Pull Request
So i made a recent PR that changes some of the announcer sounds. Its a lil too loud 4 some people. Rather than going back, tweaking the sounds, and then sending them for review again, I figure I'll just port this closed PR from TG that allows ppl to set a preference for the volumes of certain sounds. This is that PR. Most of the code is courtesy of sadboysuss's PR: https://github.com/tgstation/tgstation/pull/86932 but I debugged certain parts of it and also added a preference for announcement sounds which is what I wanted in the first place. I also removed the TTS volume part because we dont have that.

Idk how hacky this is and it's certainly not modular so I'd appreciate someone with better knowledge taking a look at it.

![image](https://github.com/user-attachments/assets/8f67dcf9-dcfb-4ac4-bd66-25580740d0f3)

## Why It's Good For The Game
Earz :3

## Changelog

:cl:Motho
qol: You can now adjust the volume of certain sound types without outright disabling them.
/:cl:

2024-10-19 09:42 UTC, tf-4 commented on code/__HELPERS/announcements.dm
> +///			if(play_sound && target.client?.prefs.read_preference(/datum/preference/toggle/sound_announcements))
Just do // DOPPLER EDIT on the end of the line or something. Having a defined start and end point kind of makes it seem like more was edited than just two lines

2024-10-19 09:43 UTC, tf-4 commented on code/__HELPERS/announcements.dm
> +///END DOPPLER EDIT
Same here

2024-10-19 09:43 UTC, tf-4 commented on code/__HELPERS/priority_announce.dm
> +		var/volume_modifier = (target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements))
And here

2024-10-19 09:43 UTC, tf-4 commented on code/__HELPERS/priority_announce.dm
> +///END DOPPLER EDIT
You get the idea

2024-10-19 09:44 UTC, tf-4 commented on code/controllers/subsystem/ambience.dm
> +///END DOPPLER EDIT
This is all one block so it's fine

2024-10-19 15:27 UTC, SomeRandomOwl requested changes
Ok so general preface here. You use way too much triple slash's. When doing comments for edits and the like you should only use double slash as triple slash is used for auto documentation which helps describe functions and variables and how they work and is interpreted by visual studio code. 

Doing so many triple slash's would have royally fucked up autodoc.

Secondly, if you only add / change a singular line, do a inline comment, keep the edit to a singular line as it makes the code significantly easier to maintain as it would help minimize any merge conflicts if there where to be any down the line.

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/__HELPERS/announcements.dm
> +			if(play_sound && target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements))
```suggestion
			if(play_sound && target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements)) //DOPPLER EDIT CHANGE - Original: if(play_sound && target.client?.prefs.read_preference(/datum/preference/toggle/sound_announcements))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/__HELPERS/announcements.dm
> +///END DOPPLER EDIT
```suggestion	
			if(player.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements)) //DOPPLER EDIT CHANGE - Original: if(player.client?.prefs.read_preference(/datum/preference/toggle/sound_announcements))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/__HELPERS/priority_announce.dm
> +///END DOPPLER EDIT
```suggestion
		if(target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements))
			SEND_SOUND(target, sound(sound_to_play, volume = volume_modifier)) //DOPPLER EDIT CHANGE - Original: SEND_SOUND(target, sound(sound_to_play))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/__HELPERS/priority_announce.dm
> +		var/volume_modifier = (target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements))
```suggestion
		var/volume_modifier = (target.client?.prefs.read_preference(/datum/preference/numeric/sound_announcements)) //DOPPLER EDIT ADDITION
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/controllers/subsystem/ambience.dm
> +///END DOPPLER EDIT
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
//	new_sound = sound(new_sound, repeat = 0, wait = 0, volume = volume, channel = CHANNEL_AMBIENCE)
// changes old function to instead grab volume from player preferences
	var/volume_modifier = (M.client?.prefs.read_preference(/datum/preference/numeric/sound_ambience_volume))/100
	new_sound = sound(new_sound, repeat = 0, wait = 0, volume = volume*volume_modifier, channel = CHANNEL_AMBIENCE)
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/controllers/subsystem/ambience.dm
> +///END DOPPLER EDIT
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
	var/volume_modifier = client.prefs.read_preference(/datum/preference/numeric/sound_ship_ambience_volume)

//	if(!sound_to_use || !(client.prefs.read_preference(/datum/preference/toggle/sound_ship_ambience)))
//		SEND_SOUND(src, sound(null, repeat = 0, wait = 0, channel = CHANNEL_BUZZ))
	if(!sound_to_use || !(client.prefs.read_preference(/datum/preference/numeric/sound_ship_ambience_volume)))
		SEND_SOUND(src, sound(null, repeat = 0, volume = volume_modifier, wait = 0, channel = CHANNEL_BUZZ))
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/controllers/subsystem/vote.dm
> +///END DOPPLER EDIT
```suggestion
		if(current_vote.vote_sound && (new_voter.prefs.read_preference(/datum/preference/numeric/sound_announcements))) //DOPPLER EDIT CHANGE - Original: if(current_vote.vote_sound && (new_voter.prefs.read_preference(/datum/preference/toggle/sound_announcements)))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/game/objects/items/devices/radio/radio.dm
> +///END DOPPLER EDIT
```suggestion
/*BEGIN DOPPLER EDIT - VOLUME MIXER
		if(radio_noise && !HAS_TRAIT(talking_living, TRAIT_DEAF) && talking_living.client?.prefs.read_preference(/datum/preference/toggle/radio_noise))
			SEND_SOUND(talking_living, 'sound/items/radio/radio_talk.ogg') */
		var/volume_modifier = (talking_living.client?.prefs.read_preference(/datum/preference/numeric/sound_radio_noise))
		if(radio_noise && !HAS_TRAIT(talking_living, TRAIT_DEAF) && volume_modifier)
			SEND_SOUND(talking_living, sound('sound/items/radio/radio_talk.ogg', volume = volume_modifier))
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/game/objects/items/devices/radio/radio.dm
> +	var/volume_modifier = (holder.client?.prefs.read_preference(/datum/preference/numeric/sound_radio_noise))
```suggestion
/* BEGIN DOPPLER EDIT - VOLUME MIXER
	if(!radio_noise || HAS_TRAIT(holder, TRAIT_DEAF) || !holder.client?.prefs.read_preference(/datum/preference/toggle/radio_noise)) */
	var/volume_modifier = (holder.client?.prefs.read_preference(/datum/preference/numeric/sound_radio_noise))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/game/objects/items/devices/radio/radio.dm
> +///		SEND_SOUND(holder, 'sound/items/radio/radio_receive.ogg')
```suggestion
//		SEND_SOUND(holder, 'sound/items/radio/radio_receive.ogg')
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/game/objects/items/devices/radio/radio.dm
> +///END DOPPLER EDIT
```suggestion
//		SEND_SOUND(holder, 'sound/items/radio/radio_important.ogg')
		SEND_SOUND(holder, sound('sound/items/radio/radio_important.ogg', volume = volume_modifier))
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/game/sound.dm
> +///END DOPPLER EDIT
```suggestion
/* BEGIN DOPPLER EDIT - VOLUME MIXER
	if(prefs && (prefs.read_preference(/datum/preference/toggle/sound_lobby)) && !CONFIG_GET(flag/disallow_title_music))
		SEND_SOUND(src, sound(SSticker.login_music, repeat = 0, wait = 0, volume = vol, channel = CHANNEL_LOBBYMUSIC)) */ // MAD JAMS
	var/volume_modifier = prefs.read_preference(/datum/preference/numeric/sound_lobby)
	if((prefs && volume_modifier) && !CONFIG_GET(flag/disallow_title_music))
		SEND_SOUND(src, sound(SSticker.login_music, repeat = 0, wait = 0, volume = volume_modifier, channel = CHANNEL_LOBBYMUSIC)) // MAD JAMS
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/client_procs.dm
> +///END DOPPLER EDIT
```suggestion
	update_ambience_pref(prefs.read_preference(/datum/preference/numeric/sound_ambience_volume)) //DOPPLER EDIT CHANGE - Original: update_ambience_pref(prefs.read_preference(/datum/preference/toggle/sound_ambience))
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/migrations/legacy_sound_toggles_migration.dm
> +	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_announcements], toggles & 1<<11)
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
//	write_preference(GLOB.preference_entries[/datum/preference/toggle/sound_ambience], toggles & 1<<2)
	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_ambience_volume], toggles & 1<<2)
//	write_preference(GLOB.preference_entries[/datum/preference/toggle/sound_announcements], toggles & 1<<11)
	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_announcements], toggles & 1<<11)
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/migrations/legacy_sound_toggles_migration.dm
> +	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_lobby], toggles & 1<<3)
```suggestion
//	write_preference(GLOB.preference_entries[/datum/preference/toggle/sound_lobby], toggles & 1<<3)
	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_lobby], toggles & 1<<3)
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/migrations/legacy_sound_toggles_migration.dm
> +///END DOPPLER EDIT
```suggestion
//	write_preference(GLOB.preference_entries[/datum/preference/toggle/sound_ship_ambience], toggles & 1<<8)
	write_preference(GLOB.preference_entries[/datum/preference/numeric/sound_ship_ambience_volume], toggles & 1<<8)
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +/datum/preference/numeric/sound_ambience_volume
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
// /datum/preference/toggle/sound_ambience
/// Controls ambience volume
/datum/preference/numeric/sound_ambience_volume
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///	savefile_key = "sound_ambience"
```suggestion
//	savefile_key = "sound_ambience"
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/controllers/subsystem/ambience.dm
> +/// changes old function to instead grab volume from player preferences
```suggestion
/*BEGIN DOPPLER EDIT - VOLUME MIXER
	new_sound = sound(new_sound, repeat = 0, wait = 0, volume = volume, channel = CHANNEL_AMBIENCE)
changes old function to instead grab volume from player preferences */
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/controllers/subsystem/ambience.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +/// default value is max/2 because 100 1x modifier, while 200 is 2x
```suggestion
// default value is max/2 because 100 1x modifier, while 200 is 2x
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_ambience/apply_to_client(client/client, value)
```suggestion
// /datum/preference/toggle/sound_ambience/apply_to_client(client/client, value)
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_announcements
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
// /datum/preference/toggle/sound_announcements
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_lobby
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
// /datum/preference/toggle/sound_lobby
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_lobby/apply_to_client_updated(client/client, value)
```suggestion
// /datum/preference/toggle/sound_lobby/apply_to_client_updated(client/client, value)
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_ship_ambience
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
// /datum/preference/toggle/sound_ship_ambience
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///	savefile_key = "sound_ship_ambience"
```suggestion
//	savefile_key = "sound_ship_ambience"
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/sound_ship_ambience/apply_to_client_updated(client/client, value)
```suggestion
// /datum/preference/toggle/sound_ship_ambience/apply_to_client_updated(client/client, value)
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +////datum/preference/toggle/radio_noise
```suggestion
//BEGIN DOPPLER EDIT - VOLUME MIXER
// /datum/preference/toggle/radio_noise
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences/sounds.dm
> +///END DOPPLER EDIT
```suggestion
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences_savefile.dm
> +///END DOPPLER EDIT
```suggestion
#define SAVEFILE_VERSION_MAX 46 // DOPPLER EDIT CHANGE - Original #define SAVEFILE_VERSION_MAX 46
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/client/preferences_savefile.dm
> +///END DOPPLER EDIT
```suggestion
//BEGIN DOPPLER EDIT Addition - VOLUME MIXER
	if (current_version < 46)
		migrate_boolean_sound_prefs_to_default_volume()
//END DOPPLER EDIT
```

2024-10-19 15:27 UTC, SomeRandomOwl commented on code/modules/mob/living/silicon/ai/ai_say.dm
> +///END DOPPLER EDIT
```suggestion			
				if(!player_mob.can_hear() || !(safe_read_pref(player_mob.client, /datum/preference/numeric/sound_announcements))) // DOPPLER EDIT CHANGE - Original: if(!player_mob.can_hear() || !(safe_read_pref(player_mob.client, /datum/preference/toggle/sound_announcements)))

```

2024-10-19 23:38 UTC, W4rd3nn commented
ill sign off on these prob tomorrow. busy 2day :3

2024-10-30 16:17 UTC, carpotoxin approved these changes

2024-10-30 16:17 UTC, merged