[NON MODULAR] [WIP!] adds libre and orion currencies
DopplerShift13/DopplerShift pull request #185
Opened 2024-10-19 22:00 UTC by crunchypretzels

## About The Pull Request

Adds Libre, a new cash currency, and Orions/Ori, a new digital currency stored on flash drives. 

## Why It's Good For The Game

i think hologram crypto is the stupidest thing imaginable

## Changelog

:cl:
add: orion, or ori, a standard cryptocurrency, which can be stored on drives from ATMs
add: libre, a fiat currency, which can be drawn from ATMs losslessly and precisely
add: ATMs, for new money-based actions
del: removes ability to draw holocurrency from ID cards
/:cl:

- [ ] add libre (port of spacetest's money)
- [ ] add orion
- [ ] add the atm from lethal
- [ ] fix atm code to allow for ori stick fabrication/filling
- [ ] tweak menus
- [ ] sprite fixes/adjustments/replacements
- [ ] balance and feedback
- [ ] iron out the bugs
- [ ] we're good

2024-11-13 01:51 UTC, Nerev4r commented
the evil is defeated

2024-11-21 01:48 UTC, Nerev4r commented
nuh uh

2024-12-30 04:34 UTC, Nerev4r commented
nuh uh

2025-02-09 18:32 UTC, crunchypretzels commented
let's get this show on the road

2025-02-10 06:16 UTC, carpotoxin requested changes
youll have to undo the map edits, we cant merge direct map edits. instead add bankmachines to a new or pre-existing automapper template (the only pre-existing one is cryo)

2025-02-10 06:16 UTC, carpotoxin commented on code/game/machinery/slotmachine.dm
> +			qdel(inserted_cash) // DOPPLER EDIT ENDS HERE (for a moment)
the nonmodular labeling in this file needs to be better

2025-02-25 15:50 UTC, Cheshify commented
This kind of killed the concept of casual transfer of money between players and all the RP associated with them. For a list of all the things that I myself have noticed:

- Thieves/Antags have a much harder time yoinking a few credits out of someone's ID when they're incapacitated because now to take some cash it involves taking their whole ass ID to an atm.
- In a similar vein of antagonism, muggings can't happen because you just can't take your cash out of your ID.
- Tipping the chef/bartender/botanist/whatever just no longer happens. What should be a quick 3 click interaction on-the-spot now requires going over to an ATM to take out 10 Libre
- Just passing someone a few credits to pay for a vending item also doesn't happen for similar reasons

I get that the idea is that people start with a paper roll of money, but this is a bandaid annoyance for a problem that the PR itself made. 

The "Why's it good for the game" also doesn't really say why this physical cash system is good when it messes with interactions.
**i think hologram crypto is the stupidest thing imaginable** 
Like yeah, so? It's debatably stupid but it serves it's purpose.

2025-03-07 00:20 UTC, dopamiin0 commented
honestly now that its been in for a while and ppl have gotten used to it and theres more ATMs and shit i dont think its nearly as annoying as originally thought its actually pretty cool

2025-05-02 01:18 UTC, crunchypretzels commented
the code isn't ideal but the idea is there. finish this and DM me on discord for USD $50

2025-05-02 01:18 UTC, closed without merging