and now for the rest of GAGS
DopplerShift13/DopplerShift pull request #21
Opened 2024-09-01 22:11 UTC by kittysmooch

## About The Pull Request

since i enabled our modular GAGS and added collars already im just gonna go through the rest of nova!gags and import everything that doesn't have a rancid sprite. it's going to take forever because it's kind of tedious work, even if it's pretty simple and mostly copy paste stuff.

## Why It's Good For The Game

playing dressup is a fundamental aspect of roleplaying games

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
:cl:

2024-09-01 22:33 UTC, kittysmooch commented
why did novarat have two different clothing toggle components man

2024-09-08 21:39 UTC, CliffracerX requested changes
This is largely looking good from what I can see, but some work is needed in the berets file

2024-09-08 21:39 UTC, CliffracerX commented on modular_doppler/modular_cosmetics/code/head/hats.dm
> +/obj/item/clothing/head/beret/medical/cmo/alt
```suggestion
```
The head berets NovaRat has are depreciated for our bespoke command berets added in #18 - these should probably go to avoid confusion

2024-09-08 21:39 UTC, CliffracerX commented on modular_doppler/modular_cosmetics/code/head/hats.dm
> +	greyscale_colors = "#FFFFFF#D15B1B"
```suggestion
	greyscale_config = /datum/greyscale_config/beret_badge
	greyscale_config_worn = /datum/greyscale_config/beret_badge/worn
	greyscale_colors = "#FFFFFF#D15B1B"
```
Needs greyscale configs updated

2024-09-08 21:39 UTC, CliffracerX commented on modular_doppler/modular_cosmetics/code/head/hats.dm
> +	greyscale_colors = "#FFFFFF#198019"
```suggestion
	greyscale_config = /datum/greyscale_config/beret_badge
	greyscale_config_worn = /datum/greyscale_config/beret_badge/worn
	greyscale_colors = "#FFFFFF#198019"
```
ditto

2024-09-08 21:47 UTC, kittysmooch commented on modular_doppler/modular_cosmetics/code/head/hats.dm
> +/obj/item/clothing/head/beret/medical/cmo/alt
understood, glory to the earth federation o7

2024-09-08 21:53 UTC, kittysmooch commented
gonna add all those w/ the loadout and vendor commit

2024-09-20 02:02 UTC, CliffracerX approved these changes
Should be clear to go at this point; I can't see anything it's in need of.

2024-09-20 02:03 UTC, merged