HELP ME HOLY SHIT (Some Sprites By Iska)
DopplerShift13/DopplerShift pull request #211
Opened 2024-11-02 19:23 UTC by Nerev4r

## About The Pull Request
I'LL FILL THIS OUT LATER WE GOTTA GET THE FUCKING SERVER UP HOLY SHIT

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
map: added/modified/removed map content
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-11-03 22:47 UTC, W4rd3nn commented
fill it out loser

2024-11-09 07:20 UTC, carpotoxin requested changes
pls also rename porcine and bovine to pig and cow.

2024-11-09 07:20 UTC, carpotoxin commented on modular_doppler/modular_customization/accessories/code/non_species_specific/porcine_accessories/porcine_snouts.dm
> +/datum/sprite_accessory/snouts/porcine
inconsistent, just name the subtype /pig

2024-11-10 09:57 UTC, carpotoxin approved these changes

2024-11-10 09:57 UTC, merged