Nerf withered insomniacs, add eye markings as penance
DopplerShift13/DopplerShift pull request #250
Opened 2024-11-25 23:16 UTC by Recoherent

## About The Pull Request

makes the eyebags from the All Nighter quirk far less visible, and adds standard markings for the undereye region they occupy and the outer eye pixel on human/anthro characters.

new eyebags
![image](https://github.com/user-attachments/assets/e9e3bed4-7439-42f5-8dbd-9baf00a47b26)
new eyebags with outereye added for cohesion on human characters
![image](https://github.com/user-attachments/assets/912ce948-cf85-4b0d-a6f7-fe822ef70961)
undereye added to replicate how dark the previous eyebags were
![image](https://github.com/user-attachments/assets/605483de-09dc-48cc-ab3e-bfb08259e6f7)

## Why It's Good For The Game

quirks with mechanically enforced visual changes are fine and all but boy howdy are these visible by default. the markings let you more easily visually work around them as well. it's character customization, baby

## Changelog

:cl:
image: The eyebags from the All Nighter quirk are now far less blatant.
add: New 'undereye' head markings, in case you want to keep your eyebags as dark as they were before.
add: New 'outer eye' head markings for all your anime human eye or multicolored anthro eye needs.
/:cl:

2024-11-26 02:02 UTC, Recoherent commented
wait no something broke with the actual files being committed what on earth

2024-11-26 02:04 UTC, Recoherent commented
or did it? i am wildly confused. this should only change four files, and definitely not the bodypart dmi in the non-modular area. i am bad at git

2024-11-27 19:59 UTC, Recoherent commented
got it set

2024-11-29 08:27 UTC, Paxilmaniac requested changes

2024-11-29 08:27 UTC, Paxilmaniac commented on code/datums/bodypart_overlays/simple_bodypart_overlay.dm
> +	icon = 'modular_doppler/modular_quirks/overwrites/icons/bodypart_overlay_simple.dmi'
document it like this
icon = 'modular_doppler/modular_quirks/overwrites/icons/bodypart_overlay_simple.dmi' // DOPPLER EDIT - whatever you want to say here
remove the comment on line 30 when you do that
also remove the single new line you added under line 31

2024-11-29 19:50 UTC, Recoherent commented on code/datums/bodypart_overlays/simple_bodypart_overlay.dm
> +	icon = 'modular_doppler/modular_quirks/overwrites/icons/bodypart_overlay_simple.dmi'
set

2024-11-29 19:56 UTC, Paxilmaniac approved these changes

2024-11-29 20:12 UTC, merged