Ports A LOT of Paxilmaniac content + Space Sappers
DopplerShift13/DopplerShift pull request #33
Opened 2024-09-06 21:40 UTC by honkpocket

## About The Pull Request

Wip

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-06 21:42 UTC, honkpocket commented
Note this includes 1 TG mirror. https://github.com/DopplerShift13/DopplerShift/pull/33/commits/e0ada34c1a96be91d375806e0506002cbc1d5927

2024-09-10 16:44 UTC, CliffracerX requested changes
Couple minor things that're off & still referencing Nova here, but once those're clear this is ready for merge

2024-09-10 16:44 UTC, CliffracerX commented on modular_doppler/colony_fabricator/sounds/attributions.txt
> +modular_nova/modules/colony_fabricator/sound/arc_furnace/arc_furnace_mid_(1 - 4).wav
Needs edited to the new modular path

2024-09-10 17:25 UTC, CliffracerX approved these changes
I believe this is clear to go, I can't see anything else that needs doing!

2024-09-10 17:25 UTC, merged