[WIP] Roleplay essentials: flavor text & records
DopplerShift13/DopplerShift pull request #64
Opened 2024-09-19 05:25 UTC by Ephemeralis

## About The Pull Request

This gets probably the last major feature before version 0 can go live into place: *flavour preferences*.

It is a mixture of stuff ported from NovaSector and new code.

Notable additions/differences:
- **Flavour text and species information is output in chat versus a new TGUI window.** This started off as a concession towards the effort involved in making an entirely new TGUI window design, but then started to gain some aesthetic merit in its own right.
- **Relevant character preferences have been split out into their own Lore page in the character creator.** Most of us are use to Nova's way of doing things (aka declaring every new preference as "non-contextual" and shoving it in the same category.

In preparation for further customization options linked to preferences later down the line, I've also cut out a `PreferenceSingle` react element that references a single preference by its chosen savefile key, allowing people who aren't very acquainted with react/typescript (me and the rest of the fucking planet) to create new pages for preferences that aren't wrapped three layers deep in autogenerated wizardry. Mothblocks did an amazing job on the auto-preference stuff, and this gets us the best of both worlds.

todo:
- [ ] Silicon examines & preferences
- [ ] Hook up records to datacore

## Changelog

:cl: yooriss
add: Flavour text via examines.
/:cl:

2024-09-21 05:57 UTC, CliffracerX requested changes
This is just about ready, just a few things need properly demarkated with doppler edit indicators so it's easier to spot our stuff in future merges.

2024-09-21 05:57 UTC, CliffracerX commented on code/datums/records/manifest.dm
> +			inject(readied_player.new_character, readied_player.client)
Doppler edit marker needed here

2024-09-21 05:57 UTC, CliffracerX commented on code/datums/records/manifest.dm
> +		age_chronological = person_client?.prefs.read_preference(/datum/preference/numeric/chronological_age),
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/datums/records/record.dm
> +	age_chronological = 18,
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/datums/records/record.dm
> +	src.age_chronological = age_chronological
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/modules/admin/admin_verbs.dm
> +			GLOB.manifest.inject(character, character.client)
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/modules/admin/verbs/admingame.dm
> +			GLOB.manifest.inject(new_character, new_character.client)
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/modules/mob/dead/new_player/new_player.dm
> +		GLOB.manifest.inject(humanc, humanc.client)
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on code/modules/mob/living/silicon/robot/examine.dm
> +#define ADD_NEWLINE_IF_NECESSARY(list) if(length(list) > 0 && list[length(list)]) { list += "" }
Ditto *probably*?  Or migrate this to one of our defines files?

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +// Larger images by text, used by flavor-text examines. No flex shenanigans.
Should demarkate this with a note about it being a doppler edit as well

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
> +// Larger images by text, used by flavor-text examines. No flex shenanigans.
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/MedicalRecords/RecordView.tsx
> +            <LabeledList.Item label="Physical Age">
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
> +import { LorePage } from './LorePage';
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
> +  Lore,
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
> +    case Page.Lore:
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
> +    doppler_lore: Record<string, unknown>;
Ditto

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
> +  TextArea,
Ditto, but comments might not work on this so if you can't no big deal

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/age.tsx
> +  description:
Ditto, though see above; might not be able to comment in the technical list here

2024-09-21 05:57 UTC, CliffracerX commented on tgui/packages/tgui/interfaces/SecurityRecords/RecordView.tsx
> +            <LabeledList.Item label="Physical Age">
Ditto

2024-09-23 11:39 UTC, honkpocket approved these changes

2024-09-24 01:24 UTC, CliffracerX approved these changes
Looks ready to go now!

2024-09-24 01:24 UTC, merged