[MODULAR] Loadout Expansions 1
DopplerShift13/DopplerShift pull request #69
Opened 2024-09-20 20:34 UTC by CliffracerX

## About The Pull Request

Adds some new goodies to the loadout for your enjoyment.
- Undersuit category!
  - Fancy pants!
  - Fancy dresses!
  - Doppler standard GAGS uniforms!
- GAGS packs & fannypack
  - GAGS-enabled backpacks, satchels, duffelbags, and messenger bags!  Back item.
  - GAGS-enabled "Slimpack" - a flat satchel variant accessible in the inhand items, with custom colors.  Inhand item.
  - GAGS-enabled fannypack, alongside a small buff to them visa-vis support for normal-size items.  Belt item.
- Added the belts from #32 as well.

## Why It's Good For The Game

Drip is nice, and current backpacks/belts can sometimes get in the way of such.

## Changelog

:cl:
add: loadout undersuit category!
add: GAGS backpacks, fannypack & some other assorted goodies
qol: fannypacks now support normal-size items.  still only 3 slots though!
/:cl:

2024-09-20 21:04 UTC, kittysmooch commented
did we fix the gags loadout icon bug?

2024-09-20 21:15 UTC, CliffracerX commented
> did we fix the gags loadout icon bug?

not yet, something I wanna look into though
it's a TG problem though at the end of the day, just one that's hard to pin down because TGUI sucks

2024-09-21 00:12 UTC, CliffracerX commented
Screenshot tests have revealed an actual problem, working on trying to fix it rn

2024-09-21 12:32 UTC, honkpocket requested changes

2024-09-21 12:32 UTC, honkpocket commented on code/modules/jobs/job_types/_job.dm
>  		/// DOPPLER SHIFT EDIT BEGIN
Misplaced comment? Should be up one line.

2024-09-21 12:32 UTC, honkpocket commented on modular_doppler/modular_cosmetics/code/storage/backpacks.dm
> +	name = "custom slimpack"
It needs to be clear that this is a smuggle satchel subtype, and can be stuffed beneath flooring.

2024-09-21 18:25 UTC, CliffracerX commented on code/modules/jobs/job_types/_job.dm
>  		/// DOPPLER SHIFT EDIT BEGIN
Check your diff version, it starts above everything that's actually edited; the ispath-istype shift was a minor syntax derp that I've since fixed

2024-09-23 10:32 UTC, honkpocket approved these changes

2024-09-23 10:32 UTC, merged